//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launcher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到启动目标文件.
        /// </summary>
        public static string BOOT_TARGET_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("BOOT_TARGET_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置项不正确！.
        /// </summary>
        public static string CONFIGURATION_ERROR {
            get {
                return ResourceManager.GetString("CONFIGURATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 补丁失败.
        /// </summary>
        public static string FAILED {
            get {
                return ResourceManager.GetString("FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请设定游戏路径！.
        /// </summary>
        public static string GAME_PATH_NOT_SET {
            get {
                return ResourceManager.GetString("GAME_PATH_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 补丁目标不正确：不是官方文件！.
        /// </summary>
        public static string INCORRECT_PATCH_TARGET {
            get {
                return ResourceManager.GetString("INCORRECT_PATCH_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key length doesn&apos;t match..
        /// </summary>
        public static string KEY_LENGTH_NO_MATCH {
            get {
                return ResourceManager.GetString("KEY_LENGTH_NO_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始游戏.
        /// </summary>
        public static string LAUNCH {
            get {
                return ResourceManager.GetString("LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原神.
        /// </summary>
        public static string MAIN_WINDOW_GAME_NAME {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_GAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告.
        /// </summary>
        public static string MAIN_WINDOW_NOTICES {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_NOTICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [在线]:.
        /// </summary>
        public static string MAIN_WINDOW_ONLINE {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原神.
        /// </summary>
        public static string MAIN_WINDOW_STATUS {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击刷新.
        /// </summary>
        public static string MAIN_WINDOW_STATUS_TOOLTIP {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_STATUS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [版本]:.
        /// </summary>
        public static string MAIN_WINDOW_VERSION {
            get {
                return ResourceManager.GetString("MAIN_WINDOW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMD5HashFromFile() fail,error.
        /// </summary>
        public static string MD5_HASH_ERROR {
            get {
                return ResourceManager.GetString("MD5_HASH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到备份文件！.
        /// </summary>
        public static string NO_BACKUP_FOUND {
            get {
                return ResourceManager.GetString("NO_BACKUP_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 官方.
        /// </summary>
        public static string PATCH_OFFICIAL {
            get {
                return ResourceManager.GetString("PATCH_OFFICIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已打补丁-ALL.
        /// </summary>
        public static string PATCH_PATCHED_ALL {
            get {
                return ResourceManager.GetString("PATCH_PATCHED_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已打补丁-Meta.
        /// </summary>
        public static string PATCH_PATCHED_META {
            get {
                return ResourceManager.GetString("PATCH_PATCHED_META", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已打补丁-UA.
        /// </summary>
        public static string PATCH_PATCHED_UA {
            get {
                return ResourceManager.GetString("PATCH_PATCHED_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到pkg_version文件！.
        /// </summary>
        public static string PKG_VERSION_NOT_FOUND {
            get {
                return ResourceManager.GetString("PKG_VERSION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备份文件不是官方文件，恢复失败！.
        /// </summary>
        public static string RESTORE_FAILED_NOT_OFFICIAL {
            get {
                return ResourceManager.GetString("RESTORE_FAILED_NOT_OFFICIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到备份文件！.
        /// </summary>
        public static string RESTORE_SUCCESS {
            get {
                return ResourceManager.GetString("RESTORE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFICIAL.
        /// </summary>
        public static string SERVER_OFFICIAL {
            get {
                return ResourceManager.GetString("SERVER_OFFICIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVATE.
        /// </summary>
        public static string SERVER_PRIVATE {
            get {
                return ResourceManager.GetString("SERVER_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭代理.
        /// </summary>
        public static string STOP_PROXY {
            get {
                return ResourceManager.GetString("STOP_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        public static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知版本的客户端！.
        /// </summary>
        public static string UNKNOWN_CLIENT_VERSION {
            get {
                return ResourceManager.GetString("UNKNOWN_CLIENT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功补丁了 UserAssembly.dll!.
        /// </summary>
        public static string USERASSEMBLY_PATCH_SUCCESS {
            get {
                return ResourceManager.GetString("USERASSEMBLY_PATCH_SUCCESS", resourceCulture);
            }
        }
    }
}
