name: DotNet Development

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - uses: nuget/setup-nuget@v1.0.6
        with:
          nuget-version: 'latest'

      - name: NuGet restore
        run: nuget restore GenshinLauncher.sln

      - name: Build
        run: msbuild GenshinLauncher.sln -p:Configuration=Release -m

      - name: Publish net70
        uses: actions/upload-artifact@v3
        id: publish_net7
        with:
          name: Launcher-NET7
          path: |
            Launcher/bin/Release/net7.0-windows
